language: go

go:
   - 1.6

install:
- export PATH=$PATH:$HOME/gopath/bin
- go get github.com/codegangsta/cli
- go get github.com/smartystreets/goconvey/convey
- go get github.com/spf13/viper
- go get github.com/lcaballero/gel
- go get github.com/jteeuwen/go-bindata/go-bindata

script: ./build.sh ci
