package main

import (
	"fmt"
	"os"
	"log"
	"strings"
	"html/template"
)

var Env = []string{
	"GOARCH",
	"GOOS",
	"GOFILE",
	"GOLINE",
	"GOPACKAGE",
	"DOLLAR",
}


func ShowEnvironment() {
	for k,v := range BuildEnv() {
		fmt.Printf("%s : %s\n", k, v)
	}
	for i,e := range os.Args {
		fmt.Printf("os.Args[%d] = %s\n", i, e)
	}
}

func BuildEnv() map[string]interface{} {
	m := make(map[string]interface{})
	for _,e := range Env {
		m[e] = os.Getenv(e)
	}
	if p,ok := m["GOPACKAGE"]; !ok || p == "" {
		m["GOPACKAGE"] = "main"
	}
	s, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	m["CWD"] = s
	m["Args"] = os.Args
	m["GEN_TAGLINE"] = fmt.Sprintf("// Generated by %s -- do not edit file.", os.Args[0])

	return m
}

func BuildFuncMap() template.FuncMap {
	return template.FuncMap{
		"title": toPascal,
		"lower": strings.ToLower,
	}
}

