package main

// Generated by genfront -- do not edit file.
//

const (
	OPTIONS = "OPTIONS"
	GET     = "GET"
	HEAD    = "HEAD"
	POST    = "POST"
	PUT     = "PUT"
	DELETE  = "DELETE"
	TRACE   = "TRACE"
	CONNECT = "CONNECT"
)

// Methods for the Rest state
func (r *Rest) Options() *Rest {
	return r.Method(OPTIONS)
}
func (r *Rest) Get() *Rest {
	return r.Method(GET)
}
func (r *Rest) Head() *Rest {
	return r.Method(HEAD)
}
func (r *Rest) Post() *Rest {
	return r.Method(POST)
}
func (r *Rest) Put() *Rest {
	return r.Method(PUT)
}
func (r *Rest) Delete() *Rest {
	return r.Method(DELETE)
}
func (r *Rest) Trace() *Rest {
	return r.Method(TRACE)
}
func (r *Rest) Connect() *Rest {
	return r.Method(CONNECT)
}

// Methods for Req state
func (r *Req) Options() *Req {
	return r.Method(OPTIONS)
}
func (r *Req) Get() *Req {
	return r.Method(GET)
}
func (r *Req) Head() *Req {
	return r.Method(HEAD)
}
func (r *Req) Post() *Req {
	return r.Method(POST)
}
func (r *Req) Put() *Req {
	return r.Method(PUT)
}
func (r *Req) Delete() *Req {
	return r.Method(DELETE)
}
func (r *Req) Trace() *Req {
	return r.Method(TRACE)
}
func (r *Req) Connect() *Req {
	return r.Method(CONNECT)
}
