package examples
// Generated by genfront -- do not edit this file.

// Methods for the Rest state
func (r *Effort) ToMap() map[string]interface{} {
  m := make(map[string]interface{})
  
  m["Id"] = r.Id
  m["Title"] = r.Title
  m["Summary"] = r.Summary
  m["Description"] = r.Description
  m["CreatedBy"] = r.CreatedBy
  m["CreatedOn"] = r.CreatedOn
  m["UpdatedBy"] = r.UpdatedBy
  m["UpdatedOn"] = r.UpdatedOn
  m["OwnedBy"] = r.OwnedBy
  m["State"] = r.State
  m["RecordStatus"] = r.RecordStatus
  return m
}
