package front_simple1
// Generated by genfront -- do not edit this file.
// 3

const (
	OPTIONS = "OPTIONS"
	GET = "GET"
	HEAD = "HEAD"
	POST = "POST"
	PUT = "PUT"
	DELETE = "DELETE"
	TRACE = "TRACE"
	CONNECT = "CONNECT"
)

// Methods for the Rest state
func (r *Rest) OPTIONS() *Rest {
	return r.Method(OPTIONS)
}
func (r *Rest) GET() *Rest {
	return r.Method(GET)
}
func (r *Rest) HEAD() *Rest {
	return r.Method(HEAD)
}
func (r *Rest) POST() *Rest {
	return r.Method(POST)
}
func (r *Rest) PUT() *Rest {
	return r.Method(PUT)
}
func (r *Rest) DELETE() *Rest {
	return r.Method(DELETE)
}
func (r *Rest) TRACE() *Rest {
	return r.Method(TRACE)
}
func (r *Rest) CONNECT() *Rest {
	return r.Method(CONNECT)
}

// Methods for Req state
func (r *Req) OPTIONS() *Req {
	return r.Method(OPTIONS)
}
func (r *Req) GET() *Req {
	return r.Method(GET)
}
func (r *Req) HEAD() *Req {
	return r.Method(HEAD)
}
func (r *Req) POST() *Req {
	return r.Method(POST)
}
func (r *Req) PUT() *Req {
	return r.Method(PUT)
}
func (r *Req) DELETE() *Req {
	return r.Method(DELETE)
}
func (r *Req) TRACE() *Req {
	return r.Method(TRACE)
}
func (r *Req) CONNECT() *Req {
	return r.Method(CONNECT)
}