package plain_icons

// Generated by genfront -- do not edit this file.

import (
	. "github.com/lcaballero/gel"
)

// <i class="home"></i>
func Home() Tag {
	return I.Class("home")
}

// <i class="home2"></i>
func Home2() Tag {
	return I.Class("home2")
}

// <i class="home3"></i>
func Home3() Tag {
	return I.Class("home3")
}

// <i class="pencil"></i>
func Pencil() Tag {
	return I.Class("pencil")
}

// <i class="pencil2"></i>
func Pencil2() Tag {
	return I.Class("pencil2")
}

// <i class="file-text"></i>
func FileText() Tag {
	return I.Class("file-text")
}

// <i class="profile"></i>
func Profile() Tag {
	return I.Class("profile")
}

// <i class="file-text2"></i>
func FileText2() Tag {
	return I.Class("file-text2")
}

// <i class="box-add"></i>
func BoxAdd() Tag {
	return I.Class("box-add")
}

// <i class="box-remove"></i>
func BoxRemove() Tag {
	return I.Class("box-remove")
}

// <i class="undo"></i>
func Undo() Tag {
	return I.Class("undo")
}

// <i class="redo"></i>
func Redo() Tag {
	return I.Class("redo")
}

// <i class="spinner"></i>
func Spinner() Tag {
	return I.Class("spinner")
}

// <i class="spinner2"></i>
func Spinner2() Tag {
	return I.Class("spinner2")
}

// <i class="spinner3"></i>
func Spinner3() Tag {
	return I.Class("spinner3")
}

// <i class="spinner9"></i>
func Spinner9() Tag {
	return I.Class("spinner9")
}

// <i class="spinner10"></i>
func Spinner10() Tag {
	return I.Class("spinner10")
}

// <i class="cogs"></i>
func Cogs() Tag {
	return I.Class("cogs")
}

// <i class="bin"></i>
func Bin() Tag {
	return I.Class("bin")
}

// <i class="bin2"></i>
func Bin2() Tag {
	return I.Class("bin2")
}

// <i class="shield"></i>
func Shield() Tag {
	return I.Class("shield")
}

// <i class="power"></i>
func Power() Tag {
	return I.Class("power")
}

// <i class="clipboard"></i>
func Clipboard() Tag {
	return I.Class("clipboard")
}

// <i class="menu"></i>
func Menu() Tag {
	return I.Class("menu")
}

// <i class="menu2"></i>
func Menu2() Tag {
	return I.Class("menu2")
}

// <i class="menu3"></i>
func Menu3() Tag {
	return I.Class("menu3")
}

// <i class="menu4"></i>
func Menu4() Tag {
	return I.Class("menu4")
}

// <i class="download2"></i>
func Download2() Tag {
	return I.Class("download2")
}

// <i class="upload2"></i>
func Upload2() Tag {
	return I.Class("upload2")
}

// <i class="plus"></i>
func Plus() Tag {
	return I.Class("plus")
}

// <i class="minus"></i>
func Minus() Tag {
	return I.Class("minus")
}

// <i class="cross"></i>
func Cross() Tag {
	return I.Class("cross")
}

// <i class="checkmark"></i>
func Checkmark() Tag {
	return I.Class("checkmark")
}

// <i class="checkmark2"></i>
func Checkmark2() Tag {
	return I.Class("checkmark2")
}

// <i class="enter"></i>
func Enter() Tag {
	return I.Class("enter")
}

// <i class="exit"></i>
func Exit() Tag {
	return I.Class("exit")
}

// <i class="checkbox-checked"></i>
func CheckboxChecked() Tag {
	return I.Class("checkbox-checked")
}

// <i class="checkbox-unchecked"></i>
func CheckboxUnchecked() Tag {
	return I.Class("checkbox-unchecked")
}

// <i class="radio-checked"></i>
func RadioChecked() Tag {
	return I.Class("radio-checked")
}

// <i class="radio-checked2"></i>
func RadioChecked2() Tag {
	return I.Class("radio-checked2")
}

// <i class="radio-unchecked"></i>
func RadioUnchecked() Tag {
	return I.Class("radio-unchecked")
}

var Icons = []Tag{
	Home(),
	Home2(),
	Home3(),
	Pencil(),
	Pencil2(),
	FileText(),
	Profile(),
	FileText2(),
	BoxAdd(),
	BoxRemove(),
	Undo(),
	Redo(),
	Spinner(),
	Spinner2(),
	Spinner3(),
	Spinner9(),
	Spinner10(),
	Cogs(),
	Bin(),
	Bin2(),
	Shield(),
	Power(),
	Clipboard(),
	Menu(),
	Menu2(),
	Menu3(),
	Menu4(),
	Download2(),
	Upload2(),
	Plus(),
	Minus(),
	Cross(),
	Checkmark(),
	Checkmark2(),
	Enter(),
	Exit(),
	CheckboxChecked(),
	CheckboxUnchecked(),
	RadioChecked(),
	RadioChecked2(),
	RadioUnchecked(),
}
